apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: kubernetes-discovery
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  # labels:
    # app: guestbook
    # tier: frontend
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  # selector can be applied automatically
  # from the labels in the pod template if not set,
  # but we are specifying the selector here to
  # demonstrate its usage.
  template:
    metadata:
      labels:
        app: kubernetes-discovery
    spec:
      hostNetwork: true
      containers:
      - name: kubernetes-discovery
        image: dgoodwin/kube-disco
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9898
        volumeMounts:
        - name: ca-secret-vol
          mountPath: /tmp/secret
          readOnly: true
      volumes:
      - name: ca-secret-vol
        secret:
            secretName: ca-secret
